# Generated by Django 5.1.7 on 2025-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='UUID',
            field=models.CharField(default='1234567890', max_length=500),
        ),
    ]
