# Generated by Django 5.1.7 on 2025-04-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='UUID',
            new_name='uuid',
        ),
    ]
